Nyah voting
csesoc/trainee_6_22T2_mafia pull request #7
Opened 2022-07-14 12:32 UTC by distrib134

I made a draft version of the GameContext file with some useful variables, haven't done the panel yet though.

(is this what I'm supposed to do??)

2022-07-15 14:02 UTC, munjoonteo requested changes

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/DayVotingMenu.js
> +import { useState, useEffect } from 'react'
Combine imports

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/DayVotingMenu.js
> +    const { players, setPlayers } = useContext(GameContext)
Combine these three lines

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/DayVotingMenu.js
> +export default DayVotingMenu
New line at end of file

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/Graveyard.js
> +export default Graveyard
Here too

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/Timer.js
> +export default Timer
Here too

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/VotePanel.js
> +export default VotePanel
Here too

2022-07-15 14:02 UTC, munjoonteo commented on client/src/components/DayVotingMenu.js
> +import '../style/DayVotingMenuStyle.css';
Where are these style files o.o

2022-07-19 03:29 UTC, distrib134 commented on client/src/components/DayVotingMenu.js
> +import '../style/DayVotingMenuStyle.css';
oops o.o

2022-07-19 05:03 UTC, munjoonteo approved these changes

2022-07-19 05:24 UTC, munjoonteo approved these changes

2022-07-19 05:25 UTC, merged